# Generated by Django 4.0.1 on 2022-03-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, null=True)),
                ('lname', models.CharField(max_length=30, null=True)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
